Adding options for ioc main
ZohebShaikh/epicscorelibs pull request #1
Opened 2024-05-10 16:55 UTC by ZohebShaikh

2024-05-15 15:35 UTC, coretl requested changes
Can also put the PVA dsos in as optional

2024-05-15 15:35 UTC, coretl commented on src/python/epicscorelibs/ioc.py
> +    for dbd,dbdpath in extra_dbd_load:
```suggestion
    base_dbd_load = (('base.dbd', DEFAULT_DBD_PATH),)
    for dbd, dbdpath in base_dbd_load + tuple(extra_dbd_load):
```

2024-05-15 15:35 UTC, coretl commented on src/python/epicscorelibs/ioc.py
>          if dbLoadDatabase(dbd, dbdpath.encode(), None):
```suggestion
        if dbLoadDatabase(dbd.encode(), dbdpath.encode(), None):
```

2024-05-15 15:35 UTC, coretl commented on src/python/epicscorelibs/ioc.py
> +def main(extra_dbd_load=[( b"PVAServerRegister.dbd",DEFAULT_DBD_PATH), (b"qsrv.dbd",DEFAULT_DBD_PATH)],extra_dso_load=[]):
```suggestion
pva_dbd_load = (("PVAServerRegister.dbd", DEFAULT_DBD_PATH), ("qsrv.dbd", DEFAULT_DBD_PATH))
pva_dso_load = ("..lib.pvAccessIOC", "..lib.qsrv")
def main(extra_dbd_load=pva_dbd_load, extra_dso_load=pva_dso_load):
```

2024-05-15 15:35 UTC, coretl commented on src/python/epicscorelibs/ioc.py
> +        _ = ctypes.CDLL(find_dso(dso), ctypes.RTLD_GLOBAL)
```suggestion
        ctypes.CDLL(find_dso(dso), ctypes.RTLD_GLOBAL) 
```

2024-05-15 15:35 UTC, coretl commented on src/python/epicscorelibs/ioc.py
>  qsrv = ctypes.CDLL(path.get_lib("qsrv"), mode=ctypes.RTLD_GLOBAL)
```suggestion
```

2024-05-16 09:19 UTC, ZohebShaikh commented
> Can also put the PVA dsos in as optional

I have made the changes for it to work I needed to put a kwargs of package -> epicscorelibs.path
I have tested that it is working 
```
python -m epicscorelibs.ioc -d epicscorelibs/test.db 
IOC Starting w/ [('epicscorelibs/test.db', '')] 
IOC dbd loaded
IOC rRDD
IOC db loaded
Starting iocInit
############################################################################
## EPICS 7.0.7.1-DEV
## Rev. 7.0.7.99.0.2
## Rev. Date 7.0.7.99.0.2
############################################################################
iocRun: All initialization complete
IOC Running
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> 
>>> 
>>> 
now exiting InteractiveConsole...
```

2024-05-17 11:06 UTC, coretl approved these changes

2024-10-03 13:40 UTC, coretl reviewed
Whitespace changes then done

2024-10-03 13:40 UTC, coretl commented on src/python/epicscorelibs/ioc.py
> +DEFAULT_DBD_PATH =os.path.join(path.base_path, "dbd")
```suggestion
DEFAULT_DBD_PATH = os.path.join(path.base_path, "dbd")
```

2024-10-03 13:40 UTC, coretl commented on src/python/epicscorelibs/ioc.py
> +        if dbLoadDatabase(dbd.encode(), dbdpath.encode(), None):
```suggestion
    base_dbd_load = (('base.dbd', DEFAULT_DBD_PATH),)
    for dbd, dbdpath in base_dbd_load + tuple(extra_dbd_load):
        if dbLoadDatabase(dbd.encode(), dbdpath.encode(), None):
```

2024-10-03 13:40 UTC, coretl commented on src/python/epicscorelibs/ioc.py
> +def main(extra_dbd_load=pva_dbd_load,extra_dso_load=pva_dso_load):
```suggestion
pva_dbd_load = (("PVAServerRegister.dbd", DEFAULT_DBD_PATH), ("qsrv.dbd", DEFAULT_DBD_PATH))
pva_dso_load = ("epicscorelibs.lib.pvAccessIOC", "epicscorelibs.lib.qsrv",)
def main(extra_dbd_load=pva_dbd_load, extra_dso_load=pva_dso_load):
```

2024-10-03 13:40 UTC, coretl commented on src/python/epicscorelibs/ioc.py
> +    start_ioc(dbs=args.database,extra_dbd_load=extra_dbd_load,extra_dso_load=extra_dso_load)
```suggestion
    start_ioc(dbs=args.database, extra_dbd_load=extra_dbd_load, extra_dso_load=extra_dso_load)
```

2024-10-07 17:52 UTC, coretl approved these changes

2024-10-23 09:01 UTC, merged